app/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)

app/__init__.py
from flask import Flask
from .hello.routes import hello_bp
from .models import db, User

def create_app():
  app = Flask(__name__)

  app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test.db'
  db.init_app(app)

  with app.app_context():
    db.create_all()

  app.register_blueprint(hello_bp)

  return app

app/hello/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from ..models import User, db

hello_bp = Blueprint('hello', __name__)

@hello_bp.route('/')
def index():
    usuarios = User.query.all()
    return render_template('index.html', usuarios=usuarios)

@hello_bp.route('/sobre')
def about():
    return "Olá, Matheus!"

@hello_bp.route('/novoUsuario', methods=['POST'])
def novo_usuario():
    nome_usuario = request.form['nome_usuario']
    if nome_usuario:
        novo_usuario = User(username=nome_usuario)
        db.session.add(novo_usuario)
        db.session.commit()
    return redirect(url_for('hello.index'))


@hello_bp.route('/removerUsuario/<int:id_usuario>', methods=['POST'])
def remover_usuario(id_usuario):
    if id_usuario:
        usuario = User.query.get(id_usuario)
        if usuario:
            db.session.delete(usuario)
            db.session.commit()
    return redirect(url_for('hello.index'))

app/templates/index.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hello World</title>
</head>

<body>
  <h1>Criar Usuario</h1>
  <form action="/novoUsuario" method="POST">
    <label for="nome_usuario">Nome Usuario:</label>
    <input type="text" id="nome_usuario" name="nome_usuario" placeholder="Nome de Usuario" required>
    <input type="submit" value="Cadastrar Usuario">
  </form>
  <h1>Usuarios</h1>
  <ul>
    {% for usuario in usuarios %}
    <li>
      <span>{{ usuario.username }}</span>
      <div class="actions">
        <form method="post" action="{{ url_for('hello.remover_usuario', id_usuario=usuario.id) }}"
          style="display:inline;">
          <button class="delete-btn" type="submit">Remover</button>
        </form>
      </div>
    </li>
    {% endfor %}
  </ul>
</body>

</html>